spring.application.name=SpringBootSecurityPostgresqlApplication
spring.datasource.url=jdbc:postgresql://pg-carlosvidal-vidalhernandezcarlosmanuel-a4ac.a.aivencloud.com:28023/defaultdb?sslmode=require
spring.datasource.username=avnadmin
spring.datasource.password=AVNS__YcSmygoGuUzlsCWJ1S

spring.jpa.database=POSTGRESQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# App Properties
bezkoder.app.jwtSecret= iloveadsoftsitoiloveadsoftsitoiloveadsoftsito
bezkoder.app.jwtExpirationMs=86400000
